version: '3.8'

services:
  monolith:
    image: morningstar-monolith:v2.0.0
    container_name: morningstar-monolith-prod
    command: ultimate.scripts.run_live --live
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - EXCHANGE_API_SECRET=${EXCHANGE_API_SECRET}
      - USE_TESTNET=false
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8000:8000"  # API REST
      - "8888:8888"  # Prometheus metrics
    volumes:
      - production_data:/app/data
      - production_logs:/app/logs
      - production_metrics:/app/ultimate/monitoring/metrics
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - morningstar-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  prometheus:
    image: prom/prometheus:v2.36.0
    container_name: morningstar-prometheus-prod
    volumes:
      - ./ultimate/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - monolith
    networks:
      - morningstar-network
    deploy:
      resources:
        limits:
          memory: 2G

  grafana:
    image: grafana/grafana:9.3.6
    container_name: morningstar-grafana-prod
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ultimate/monitoring/grafana_dashboards:/etc/grafana/provisioning/dashboards
      - ./ultimate/monitoring/grafana_datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - morningstar-network
    deploy:
      resources:
        limits:
          memory: 1G

  telegram-bot:
    image: morningstar-monolith:v2.0.0
    container_name: morningstar-telegram-bot
    command: ultimate.scripts.run_telegram_bot
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - production_data:/app/data:ro
      - production_logs:/app/logs:ro
      - production_metrics:/app/ultimate/monitoring/metrics:ro
    restart: unless-stopped
    depends_on:
      - monolith
    networks:
      - morningstar-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  morningstar-network:
    driver: bridge

volumes:
  production_data:
  production_logs:
  production_metrics:
  prometheus_data:
  grafana_data: 