global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'morningstar'
    scrape_interval: 5s
    static_configs:
      - targets: ['monolith:8888']
        labels:
          instance: 'monolith'
          service: 'morningstar' 